replace 'grep -v ...': with '! grep ...'
the former wasn't properly checking for success or error state after
running ssh

diff --git a/kaya b/kaya
--- a/kaya
+++ b/kaya
@@ -144,10 +144,10 @@ ${kaya_protocol_version}
 ${password}
 EOF
 
-    # confirm that the SSH session completed
-    if tail -1 "${log_dump}" | grep -v -e "^KAYA_SUCCESSFUL_BACKUP_MESSAGE" -e "^kaya-client: command exit code" ; then
-	echo "kaya: backup interrupted or failed to complete" >&2
-	exit 1
+    # confirm that the SSH session completed (ssh client often exits 0, even if it's killed)
+    if ! tail -1 "${log_dump}" | grep -q -E -e "^KAYA_SUCCESSFUL_BACKUP_MESSAGE" -e "^kaya-client: command exit code" ; then
+        echo "kaya: backup interrupted or failed to complete" >&2
+        exit 1
     fi
 }
 
