send protocol version # for checking compatibility
the protocol version number allows us to print errors about mismatched
versions if the client-server API changes in the future

diff --git a/kaya-client b/kaya-client
--- a/kaya-client
+++ b/kaya-client
@@ -23,6 +23,14 @@ shopt -s inherit_errexit 2>/dev/null ||: # ignore fail in bash < 4.4
 set -eE -o pipefail
 trap 'echo "$0:$LINENO:error: \"$BASH_COMMAND\" exit status: $?, PIPESTATUS: ${PIPESTATUS[*]}" >&2' ERR
 
+read -r kaya_protocol_version
+
+if [[ $kaya_protocol_version != 1 ]] ; then
+    echo "kaya-client: error: mismatched protocol version with kaya" >&2
+    echo "kaya-client: error: kaya protocol version: ${kaya_protocol_version} kaya-client protocol version: 1" >&2
+    exit 1
+fi
+
 read -r password
 
 port="$1"
