fix error message

diff --git a/kaya b/kaya
--- a/kaya
+++ b/kaya
@@ -61,7 +61,7 @@ function get_params() {
                 break
                 ;;
             -*)
-                echo "kaya: error: unrecognized option $key" >&2
+                echo "kaya: error: unrecognized argument: $key" >&2
                 kaya_usage 1
                 ;;
             *)
@@ -86,7 +86,7 @@ function get_params() {
         # currently the only option is to backup
         ;;
         *)
-            echo "kaya: error: missing action argument" >&2
+            echo "kaya: error: invalid action argument: $action" >&2
             kaya_usage 1
             ;;
     esac
